import gleam/string
import solve_2025_07

const input = "
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"

pub fn part_one_test() {
  let result =
    input
    |> string.trim
    |> solve_2025_07.part_one
  assert result == 21
}

pub fn part_two_test() {
  let result =
    input
    |> string.trim
    |> solve_2025_07.part_two
  assert result == 40
}
